[project]
name = "inatlabel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "label-studio>=1.15.0",
    "pyinaturalist>=0.19.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
